name: Build AyuGram Linux
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/telegramdesktop/admin-linux:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build AyuGram
        run: |
          mkdir build && cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
          ninja

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AyuGram-Linux-Binary
          path: build/AyuGram
