name: Build AyuGram Linux
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/telegramdesktop/tdesktop/centos_env:latest
      options: --user root # Принудительно даем права для совместимости с GitHub Actions
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build AyuGram
        run: |
          # Переходим в рабочую директорию и запускаем официальный скрипт сборки
          cd $GITHUB_WORKSPACE
          /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh
        continue-on-error: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AyuGram-Linux-Binary
          path: out/Release/AyuGram
